name: snapsell
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

  # ------------- Packages -------------- #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.18.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  flutter_dropzone: ^3.0.7
  flutter_typeahead: ^5.2.0
  connectivity_plus: ^5.0.1
  multi_select_flutter: ^4.1.3
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.5
  smooth_page_indicator: ^1.1.0

  # Web Specific
  web: ^0.5.1
  http: ^1.1.2
  html: ^0.15.4
  fl_chart: ^0.66.2
  data_table_2: ^2.5.9
  url_strategy: ^0.2.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  firebase_storage: ^11.5.1

  # ------------- Packages End ------------ #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # ------------ Local Assets ------------- #
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - assets/icons/brands/
    - assets/icons/categories/

  # ----------- Local Fonts --------------- #
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 800
